command:
  - python3
  - ${program}
  - ${args_no_boolean_flags}
method: grid
name: evaluation
program: helper_scripts/unified_sweep_env.py
project: full_evaluation

parameters:
  dataset_source:
    value: d4rl
  dataset:
    values:
      - walker2d-medium-replay-v2
      - pen-cloned-v1
      - antmaze-large-diverse-v2
  algorithm: # name of algo, must correspond to config in configs/
    values:
      - augmented_methods/unified_uawac
      - augmented_methods/unified_ucql
  seed:
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  num_updates: # if set, will train for this many steps, otherwise default to 1mil
    value: 1_000_000
  num_eval_eps: # final eval eps
    value: 1000
