command:
  - python3
  - ${program}
  - ${args_no_boolean_flags}
method: grid
name: evaluation
program: helper_scripts/unified_sweep_env.py
entity: ahoj
project: full_evaluation

parameters:
  dataset_source:
    value: d4rl
  dataset:
    values:
      - hopper-medium-v2
      - halfcheetah-medium-expert-v2
      - walker2d-medium-replay-v2
      - pen-human-v1
      - pen-cloned-v1
      - pen-expert-v1
      - antmaze-large-diverse-v2
      - maze2d-large-v1
      - kitchen-mixed-v0
  algorithm: # name of algo, must correspond to config in configs/
    values:
      - unified_sacn
      - unified_edac
      - unified_msg
      - unified_awac
      - unified_pbrl
      - unified_cql
      - bc # baselines from Unifloral
      - rebrac
      - iql
  runs:
    value: 20 # Impliticly use seeds [1, #runs] to train policies
  sampling_seed:
    value: 42 # used for hyperaparameter sampling, not for training 
  num_updates: # if set, will train for this many steps, otherwise default to 1mil
    value: 1_000_000
  num_eval_eps:
    value: 1000
