command:
  - python3
  - ${program}
  - ${args_no_boolean_flags}
method: grid
name: evaluation
program: helper_scripts/unified_sweep_env.py
project: full_evaluation

parameters:
  dataset_source:
    value: d4rl
  dataset:
    values:
      - pen-cloned-v1
      - antmaze-large-diverse-v2
  algorithm: # name of algo, must correspond to config in configs/
    values:
      - unified_pbrl2
  seed:
    values: [0,1,2]
      #value: 0
  num_updates: # if set, will train for this many steps, otherwise default to 1mil
    value: 500_000
  num_eval_eps: # final eval eps
    value: 100
