command:
  - python3
  - ${program}
  - ${args_no_boolean_flags}
entity: ahoj
method: random
name: mean_awac_lower_beta
program: algorithms/unified.py
project: awac-30-eval-deterministic

parameters:
  # --- Experiment ---
  seed:
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  dataset_source:
    value: d4rl
  dataset_name:
    values: 
      - hopper-medium-v2
  algorithm:
    value: u_awac
  num_updates:
    value : 1_000_000
  eval_interval:
    value: 10_000
  eval_workers:
    value: 8
  eval_final_episodes:
    value: 1000

  # --- Logging ---
  log:
    value: true
  checkpoint_dir:
    value: "./checkpoints/u_awac"
  checkpoint:
    value: true
  # --- Generic optimization ---
  lr:
    value: 3e-4
  actor_lr:
    value: 3e-4
  batch_size:
    value: 256
  gamma:
    value: 0.99
  polyak_step_size:
    value: 0.005

  no_entropy_bonus:
    value: true

  shared_targets:
    values:
      - false

  # --- PBRL specific ---
  critic_regularizer:
    values: 
      - "none"

  beta_id:
    values: 
      - 0.005
      - 0.01
      - 0.025
      - 0.05

  pi_operator:
    value: "awr"

  awr_temperature:
    values: 
      - 1.0
      - 0.33
      - 0.01

  num_critics:
    values: 
      - 10
      - 30



  
