command:
  - python3
  - ${program}
  - ${args_no_boolean_flags}
entity: ahoj
method: random
name: independent_awac
program: algorithms/unified.py
project: awac-unifloral-eval

parameters:
  # --- Experiment ---
  seed:
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  dataset_source:
    value: d4rl
  dataset_name:
    values: 
      - hopper-medium-v2
  algorithm:
    value: awac
  num_updates:
    value : 1_000_000
  eval_interval:
    value: 10_000
  eval_workers:
    value: 8
  eval_final_episodes:
    value: 1000

  # --- Logging ---
  log:
    value: true
  checkpoint:
    value: true
  checkpoint_dir:
    value: "./checkpoints/awac"
  # --- Generic optimization ---
  lr:
    value: 3e-4
  actor_lr:
    value: 3e-4
  batch_size:
    value: 256
  gamma:
    value: 0.99
  polyak_step_size:
    value: 0.005
  no_entropy_bonus:
    value: true

  # 2 shared critics
  shared_targets:
    values:
      - true
  num_critics:
    value: 
      - 2
  critic_regularizer:
    values: 
      - "none"
  # policy improvement
  pi_operator:
    value: "awr"

  awr_temperature:
    values: 
      - 1.0

  # changes
  log_q_values:
    value: true
